//@ pragma ShellId mg
//@ pragma StateDir $BASE/mg
//@ pragma UseQApplication
//@ pragma DefaultEnv QSG_RENDER_LOOP=threaded

// mg - a Material 3 shell for Hyprland.
//
// Three surfaces: a fixed vertical bar, a launcher, and notifications.
// Deliberately NOT here: dashboard, OSD, lockscreen, session menu. hyprlock
// stays the lock implementation.
//
// Colours come from $XDG_STATE_HOME/theme/scheme.json, generated by matugen
// from the current wallpaper; the shell watches that file and recolours live.

import Quickshell
import qs.modules.bar
import qs.modules.launcher
import qs.modules.notifications

ShellRoot {
    // Keep the on-screen reload/error toast during development: a QML syntax
    // error otherwise shows up only as a bar that silently failed to update.
    settings.watchFiles: true

    Variants { model: Quickshell.screens; delegate: Bar {} }
    Variants { model: Quickshell.screens; delegate: Launcher {} }
    Variants { model: Quickshell.screens; delegate: Notifications {} }
}
