-- GENERATED by matugen - do not edit. Consumed by nvim/colors/dyn.lua.
--
-- base00..base07 (backgrounds, greys, foreground) are built from the M3
-- surface ladder, which matugen tone-maps properly and which carries no
-- semantics. base08..base0F are PINNED.
--
-- Why pinned: matugen does emit its own base16 block, and it is unusable.
-- Measured on this machine, base08..base0f came back as #424c8e #25325f
-- #0a1837 #020c27 #1c2340 #050b1d #111526 #240f1a - eight shades of dark
-- navy, with no red, green, yellow or blue anywhere. Syntax highlighting
-- built on that is unreadable, and diff colours would follow the wallpaper.
return {
  base16 = {
    base00 = "{{colors.surface.default.hex}}",                    -- bg
    base01 = "{{colors.surface_container.default.hex}}",          -- lighter bg, status
    base02 = "{{colors.surface_container_high.default.hex}}",     -- selection bg
    base03 = "{{colors.outline.default.hex}}",                    -- comments, invisibles
    base04 = "{{colors.on_surface_variant.default.hex}}",         -- dark fg
    base05 = "{{colors.on_surface.default.hex}}",                 -- default fg
    base06 = "{{palettes.neutral._90.hex}}",                      -- light fg
    base07 = "{{palettes.neutral._95.hex}}",                      -- lightest fg
    base08 = "#e05561",  -- variables, diff-deleted, tags
    base09 = "#d98e48",  -- integers, constants
    base0A = "#d9c26a",  -- classes, search bg
    base0B = "#8cc265",  -- strings, diff-added
    base0C = "#5fb3b3",  -- regex, escapes
    base0D = "#5f9fd8",  -- functions, methods
    base0E = "#c495d0",  -- keywords, diff-changed
    base0F = "#be5046",  -- deprecated, embedded
  },

  -- Never wallpaper-driven: a human must read these at a glance.
  semantic = {
    error  = "#e05561",
    warn   = "#d9c26a",
    info   = "{{colors.primary.default.hex}}",
    hint   = "{{colors.tertiary.default.hex}}",
    add    = "#8cc265",
    change = "#d9c26a",
    delete = "#e05561",
  },

  -- Free to follow the wallpaper: chrome, not meaning.
  m3 = {
    primary               = "{{colors.primary.default.hex}}",
    on_primary            = "{{colors.on_primary.default.hex}}",
    primary_container     = "{{colors.primary_container.default.hex}}",
    on_primary_container  = "{{colors.on_primary_container.default.hex}}",
    tertiary              = "{{colors.tertiary.default.hex}}",
    on_tertiary           = "{{colors.on_tertiary.default.hex}}",
    tertiary_container    = "{{colors.tertiary_container.default.hex}}",
    on_tertiary_container = "{{colors.on_tertiary_container.default.hex}}",
    outline               = "{{colors.outline.default.hex}}",
    surface_container     = "{{colors.surface_container.default.hex}}",
  },
}
