# GENERATED by matugen - do not edit.
# Semantic styles (command/error/string) are PINNED: a green "this is a valid
# command" cue must not become whatever hue the wallpaper happens to be.
ZSH_HIGHLIGHT_HIGHLIGHTERS=(main brackets cursor)
typeset -gA ZSH_HIGHLIGHT_STYLES

ZSH_HIGHLIGHT_STYLES[unknown-token]='fg=#e05561,bold'
for _k in command builtin function alias suffix-alias global-alias reserved-word hashed-command; do
  ZSH_HIGHLIGHT_STYLES[$_k]='fg=#8cc265'
done
unset _k
ZSH_HIGHLIGHT_STYLES[precommand]='fg=#8cc265,italic'
ZSH_HIGHLIGHT_STYLES[single-quoted-argument]='fg=#d9c26a'
ZSH_HIGHLIGHT_STYLES[double-quoted-argument]='fg=#d9c26a'
ZSH_HIGHLIGHT_STYLES[dollar-quoted-argument]='fg=#d9c26a'

# Wallpaper-driven: chrome, not meaning.
ZSH_HIGHLIGHT_STYLES[path]='fg={{colors.on_surface.default.hex}},underline'
ZSH_HIGHLIGHT_STYLES[comment]='fg={{colors.outline.default.hex}},italic'
ZSH_HIGHLIGHT_STYLES[default]='fg={{colors.on_surface.default.hex}}'
ZSH_HIGHLIGHT_STYLES[single-hyphen-option]='fg={{colors.tertiary.default.hex}}'
ZSH_HIGHLIGHT_STYLES[double-hyphen-option]='fg={{colors.tertiary.default.hex}}'
ZSH_HIGHLIGHT_STYLES[autodirectory]='fg={{colors.tertiary.default.hex}},italic'
ZSH_HIGHLIGHT_STYLES[back-quoted-argument]='fg={{colors.secondary.default.hex}}'
ZSH_HIGHLIGHT_STYLES[commandseparator]='fg={{colors.on_surface_variant.default.hex}}'
ZSH_HIGHLIGHT_STYLES[redirection]='fg={{colors.on_surface_variant.default.hex}}'
ZSH_HIGHLIGHT_STYLES[bracket-level-1]='fg={{colors.primary.default.hex}}'
ZSH_HIGHLIGHT_STYLES[bracket-level-2]='fg={{colors.secondary.default.hex}}'
ZSH_HIGHLIGHT_STYLES[bracket-level-3]='fg={{colors.tertiary.default.hex}}'
ZSH_HIGHLIGHT_STYLES[cursor-matchingbracket]='standout'
